load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "common",
    srcs = [
        "__init__.py",
        "config.py",
        "exceptions.py",
        "schemas.py",
        "types.py",
    ],
    imports = ["../.."],
    visibility = [
        "//platform/vision/src:__subpackages__",
        "//platform/vision/tests:__subpackages__",
    ],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "@pip//pydantic",
        "@pip//pyyaml",
    ],
)

py_test(
    name = "types_test",
    srcs = ["types_test.py"],
    imports = ["../.."],
    deps = [":common"],
)
