load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "common",
    srcs = [
        "__init__.py",
        "config.py",
        "exceptions.py",
        "pipelines.py",
        "schemas.py",
        "types.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "//platform/ontology/src/galadril_ontology/backends/terminus",
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/pipeline/src/galadril_pipeline/config",
        "@pip//pydantic",
        "@pip//pyyaml",
        "@pip//structlog",
    ],
)
