load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "resources",
    srcs = [
        "__init__.py",
        "causal.py",
        "config.py",
        "kafka.py",
        "postgres.py",
        "s3.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "//platform/vision/src/galadril_vision/causal",
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "//platform/vision/src/galadril_vision/connectors/s3",
        "@pip//confluent_kafka",
        "@pip//dagster",
        "@pip//orjson",
        "@pip//pydantic",
    ],
)
