load("//:build/setup.bzl", "define_root_targets")

licenses(["notice"])  # BSD-3-Clause

exports_files([
    "VERSION.txt",
    "CODEOWNERS",
    "build/uv-project.toml",
    "rustfmt.toml",
])

# gazelle:exclude .venv
# gazelle:exclude target

define_root_targets(name = "galadril")

alias(
    name = "protoc",
    actual = "@protobuf//:protoc",
    visibility = ["//visibility:public"],
)

alias(
    name = "well_known_types",
    actual = "@protobuf//:well_known_type_protos",
    visibility = ["//visibility:public"],
)
