load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "text",
    srcs = [
        "__init__.py",
        "eru.py",
        "glm_ocr.py",
        "got_ocr.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//machine-learning/eru/src/eru",
        "//machine-learning/eru/src/eru/extractor",
        "//machine-learning/eru/src/eru/llm",
        "//machine-learning/eru/src/eru/logic",
        "//machine-learning/eru/src/eru/reasoner",
        "//machine-learning/galadril-inference/src/galadril_inference/common",
        "//machine-learning/galadril-inference/src/galadril_inference/models",
        "@pip//huggingface_hub",
        "@pip//numpy",
        "@pip//pillow",
        "@pip//pydantic",
        "@pip//structlog",
        "@pip//torch",
        "@pip//transformers",
    ],
)
