load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "llm",
    srcs = [
        "__init__.py",
        "llamacpp.py",
        "outlines_base.py",
        "reference_resolver.py",
        "semantic_normalizer.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//machine-learning/eru/src/eru",
        "//machine-learning/eru/src/eru/common",
        "@pip//llama_cpp_python",
        "@pip//pydantic",
        "@pip//structlog",
    ],
)
