load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "s3",
    srcs = [
        "__init__.py",
        "client.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "@pip//aioboto3",
        "@pip//boto3",  # keep
        "@pip//botocore",
        "@pip//structlog",
    ],
)
