[package]
name = "galadril-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
opentelemetry = "0.32"
opentelemetry-appender-tracing = "0.32"
opentelemetry-otlp = { version = "0.32", default-features = false, features = ["grpc-tonic", "logs", "metrics", "trace"] }
opentelemetry_sdk = { version = "0.32", features = ["logs", "metrics", "trace"] }
tracing = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
