load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_parser",
    srcs = ["test_parser.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_events",
    srcs = ["test_events.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/pipeline/src/galadril_pipeline/config",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_routing",
    srcs = ["test_routing.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/pipeline/src/galadril_pipeline/config",
        "@pip//pytest",
    ],
)
