load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_parser",
    srcs = ["test_parser.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_vision_pipeline_e2e",
    srcs = ["test_vision_pipeline_e2e.py"],
    deps = [
        "@pip//dagster",
        "@pip//pytest",
    ],
)
