load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_batch",
    srcs = ["test_batch.py"],
    deps = ["//platform/pipeline/src/galadril_pipeline/runtime"],
)

py_test(
    name = "test_engine",
    srcs = ["test_engine.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "@pip//pytest",
    ],
)
