[package]
name = "intake"
version = "0.1.1"
edition = "2024"

[dependencies]
aws-config = { version = "1.8", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.135"
rdkafka = { version = "0.39", features = ["tokio"] }
schema_registry_converter = { version = "4.9", features = ["avro", "blocking"] }
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"
serde = { workspace = true }
serde_json = "1"
apache-avro = { version = "0.21", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.23", features = ["v4"] }
anyhow = { workspace = true }
csv = "1.4"
regex = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = { version = "0.8", features = ["multipart"] }
jsonwebtoken = { version = "10", features = ["aws_lc_rs"] }
loth = { git = "https://github.com/Aeluin-Technologies/loth.git", rev = "cfba8e891bf59bf1d88443d2f7400e561cdd55d0" }
secrecy = { version = "0.10", features = ["serde"] }
urlencoding = "2"
sanitize-filename = "0.6"
config = { version = "0.15", features = ["yaml"] }
bytes = "1.12"
moka = { version = "0.12", features = ["future"] }
mimalloc = { workspace = true }

[dev-dependencies]
mockall = "0.15"
