# gazelle:ignore

filegroup(
    name = "fixtures",
    srcs = [
        "connectors.yaml",
        "e2e_inference_model.py",
        "otel-collector.yaml",
        "tempo.yaml",
    ],
    visibility = ["//tests/e2e:__pkg__"],
)

filegroup(
    name = "empirical_data",
    srcs = [
        "retail.csv",
        "trial.csv",
    ],
    visibility = ["//tests/e2e:__pkg__"],
)
