load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_outlines",
    srcs = ["test_outlines.py"],
    deps = [
        "//machine-learning/eru/src/eru",
        "//machine-learning/eru/src/eru/common",
        "//machine-learning/eru/src/eru/reasoner",
        "@pip//pydantic",
    ],
)

py_test(
    name = "test_relation_candidates",
    srcs = ["test_relation_candidates.py"],
    deps = [
        "//machine-learning/eru/src/eru",
        "//machine-learning/eru/src/eru/common",
        "//machine-learning/eru/src/eru/reasoner",
        "@pip//pydantic",
    ],
)
