load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "compiler",
    srcs = [
        "__init__.py",
        "assets.py",
        "resources.py",
    ],
    imports = ["../.."],
    visibility = [
        "//platform/pipeline/src:__subpackages__",
        "//platform/pipeline/tests:__subpackages__",
    ],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/pipeline/src/galadril_pipeline/resources",
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "@pip//dagster",
        "@pip//pydantic",
        "@pip//structlog",
    ],
)
