load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_defs",
    srcs = ["test_defs.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_executor",
    srcs = ["test_executor.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_router",
    srcs = ["test_router.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/runtime",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_runner",
    srcs = ["test_runner.py"],
    deps = [
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)
