load("@rules_python//python:defs.bzl", "py_test")

package(default_visibility = ["//platform/vision/tests:__pkg__"])

py_test(
    name = "test_ledger",
    srcs = ["test_ledger.py"],
    legacy_create_init = False,
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)
