load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_ledger",
    srcs = ["test_ledger.py"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/pipeline/src/galadril_pipeline/config",
        "//platform/vision/src/galadril_vision/pipeline",
        "@pip//pytest",
    ],
)
