load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_config",
    srcs = ["test_config.py"],
    deps = ["//platform/vision/src/galadril_vision/common"],
)

py_test(
    name = "test_s3",
    srcs = ["test_s3.py"],
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/s3",
        "@pip//pyarrow",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_telemetry",
    srcs = ["test_telemetry.py"],
    deps = [
        "//platform/vision/src/galadril_vision/telemetry",
        "@pip//opentelemetry_api",
        "@pip//opentelemetry_sdk",
        "@pip//pytest",
        "@pip//structlog",
    ],
)

py_test(
    name = "test_types",
    srcs = ["test_types.py"],
    deps = ["//platform/vision/src/galadril_vision/common"],
)
