load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_config",
    srcs = ["test_config.py"],
    data = ["//examples:pipeline_configuration"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_main",
    srcs = ["test_main.py"],
    deps = [
        "//platform/vision/src/galadril_vision",
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/streaming",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_runtime",
    srcs = ["test_runtime.py"],
    deps = [
        "//platform/vision/src/galadril_vision",
        "//platform/vision/src/galadril_vision/common",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_s3",
    srcs = ["test_s3.py"],
    deps = [
        "//platform/vision/src/galadril_vision/connectors/s3",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_telemetry",
    srcs = ["test_telemetry.py"],
    deps = [
        "//platform/vision/src/galadril_vision/telemetry",
        "@pip//opentelemetry_api",
        "@pip//opentelemetry_sdk",
        "@pip//pytest",
        "@pip//structlog",
    ],
)

py_test(
    name = "test_types",
    srcs = ["test_types.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_pipeline_storage",
    srcs = ["test_pipeline_storage.py"],
    legacy_create_init = False,
    deps = [
        "//platform/ontology/src/galadril_ontology/backends/terminus",
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/streaming",
        "@pip//pytest",
    ],
)
