load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "udfs",
    srcs = [
        "download.py",
        "inference.py",
        "resolve.py",
        "sink.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//platform/vision/src/galadril_vision/compute/udfs",
        "@pip//daft",
        "@pip//numpy",
        "@pip//pytest",
    ],
)
