load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "discovery",
    srcs = [
        "__init__.py",
        "pcmci.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "@pip//joblib",  # keep
        "@pip//networkx",
        "@pip//numpy",
        "@pip//pandas",
        "@pip//structlog",
        "@pip//tigramite",
    ],
)
