load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "embedding",
    srcs = [
        "__init__.py",
        "bgem3.py",
        "qwen3.py",
        "siglip.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/common",
        "//machine-learning/galadril-inference/src/galadril_inference/models",
        "@pip//huggingface_hub",
        "@pip//llama_cpp_python",
        "@pip//numpy",
        "@pip//structlog",
        "@pip//tokenizers",
        "@pip//transformers",
    ],
)
