load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "osint",
    srcs = [
        "__init__.py",
        "geoclip.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/common",
        "//machine-learning/galadril-inference/src/galadril_inference/models",
        "@pip//geoclip",
        "@pip//structlog",
        "@pip//torch",
    ],
)
