filegroup(
    name = "database_initialization",
    srcs = [
        "init-scripts/01-init-spicedb.sh",
        "init-scripts/02-init-galadril-roles.sh",
        "init-scripts/03-init-terminusdb.sh",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "compose_configuration",
    srcs = glob([
        "*.yaml",
        "init-scripts/*.sh",
    ]),
    visibility = ["//visibility:public"],
)
