services:
  postgres:
    image: ghcr.io/aeluin-technologies/galadril-database:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=galadril_dev
      - PGDATA=/home/postgres/pgdata/data
      - TIMESCALEDB_TELEMETRY=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d galadril_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/home/postgres/pgdata/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  spicedb-migrate:
    image: authzed/spicedb:v1.53.0
    container_name: spicedb_migrate
    environment:
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgres://postgres:postgres@postgres:5432/spicedb?sslmode=disable
    command: ["datastore", "migrate", "head"]
    depends_on:
      postgres:
        condition: service_healthy

  spicedb:
    image: authzed/spicedb:v1.53.0
    container_name: spicedb
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - SPICEDB_GRPC_PRESHARED_KEY=secret_key
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgres://postgres:postgres@postgres:5432/spicedb?sslmode=disable
    command: ["serve"]
    depends_on:
      spicedb-migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
