services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.158.0
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ../observability/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:3.0.3
    container_name: tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ../observability/tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"

  mimir:
    image: grafana/mimir:3.1.4
    container_name: mimir
    restart: unless-stopped
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ../observability/mimir.yaml:/etc/mimir.yaml:ro
      - mimir-data:/data
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.6.15
    container_name: loki
    restart: unless-stopped
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  pyroscope:
    image: grafana/pyroscope:2.2.1
    container_name: pyroscope
    restart: unless-stopped
    volumes:
      - pyroscope-data:/data
    ports:
      - "4040:4040"

  profiler:
    image: grafana/alloy:v1.18.1
    container_name: profiler
    restart: unless-stopped
    user: root
    pid: host
    privileged: true
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ../observability/alloy.config:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - alloy-symbol-cache:/tmp/symb-cache
      - alloy-data:/var/lib/alloy/data
    depends_on:
      - pyroscope

  grafana:
    image: grafana/grafana:13.0-slim
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - mimir
      - tempo
      - loki
      - pyroscope
    volumes:
      - ../observability/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3005:3000"

volumes:
  alloy-data:
  alloy-symbol-cache:
  grafana-data:
  mimir-data:
  pyroscope-data:
  tempo-data:
