load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "ontology",
    srcs = [
        "__init__.py",
        "base.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "//platform/vision/src/galadril_vision/common",
    ],
)
