-- Installs PostgreSQL extensions required by Vision operational persistence.

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE EXTENSION IF NOT EXISTS vector CASCADE;
CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;
CREATE EXTENSION IF NOT EXISTS age CASCADE;
CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
CREATE EXTENSION IF NOT EXISTS plpython3u CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_wait_sampling CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_repack CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_trgm CASCADE;
