load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "galadril_registry_api",
    srcs = [
        "__init__.py",
        "client.py",
        "registry_pb2.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pip//grpcio",
        "@pip//protobuf",
        "@pip//pydantic",
    ],
)
