load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "kafka",
    srcs = [
        "__init__.py",
        "producer.py",
        "resolver.py",
        "schemas.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "@pip//attrs",  # keep
        "@pip//authlib",  # keep
        "@pip//cachetools",  # keep
        "@pip//confluent_kafka",
        "@pip//fastavro",  # keep
        "@pip//httpx",  # keep
        "@pip//orjson",  # keep
        "@pip//pydantic",
        "@pip//structlog",
    ],
)
