load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "identity",
    srcs = [
        "__init__.py",
        "licorne.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "@pip//orjson",
        "@pip//structlog",
    ],
)
