load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "galadril_ontology",
    srcs = [
        "__init__.py",
        "errors.py",
        "identity.py",
        "model.py",
        "runtime.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pip//pydantic",
        "@pip//structlog",
    ],
)
