load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "postgres",
    srcs = [
        "__init__.py",
        "client.py",
        "graph.py",
        "models.py",
        "vector.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "@pip//geoalchemy2",
        "@pip//orjson",
        "@pip//pgvector",
        "@pip//psycopg",
        "@pip//psycopg_binary",  # keep
        "@pip//psycopg_pool",
        "@pip//sqlalchemy",
        "@pip//structlog",
    ],
)
