load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pipeline",
    srcs = [
        "__init__.py",
        "client.py",
        "defs.py",
        "executor.py",
        "router.py",
        "runner.py",
    ],
    imports = ["../.."],
    visibility = [
        "//platform/vision/src:__subpackages__",
        "//platform/vision/tests:__subpackages__",
    ],
    deps = [
        "//platform/pipeline/src/galadril_pipeline",
        "//platform/vision/src/galadril_vision/causal",
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/compute/udfs",
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "//platform/vision/src/galadril_vision/connectors/s3",
        "//platform/vision/src/galadril_vision/telemetry",
        "@pip//aiohttp",
        "@pip//boto3",
        "@pip//botocore",
        "@pip//daft",
        "@pip//dagster",
        "@pip//pydantic",
        "@pip//pyyaml",
        "@pip//structlog",
    ],
)
