load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "image",
    srcs = [
        "__init__.py",
        "face_recognition.py",
        "grounded_sam.py",
        "owl.py",
        "prithvi.py",
    ],
    imports = ["../../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/common",
        "//machine-learning/galadril-inference/src/galadril_inference/models",
        "@pip//huggingface_hub",
        "@pip//insightface",
        "@pip//numpy",
        "@pip//onnxruntime",
        "@pip//pillow",
        "@pip//structlog",
        "@pip//torch",
        "@pip//transformers",
    ],
)
