load("@rules_python//python:defs.bzl", "py_test")

package(default_visibility = ["//platform/vision/tests:__pkg__"])

py_test(
    name = "test_client",
    srcs = ["test_client.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_vector",
    srcs = ["test_vector.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_graph",
    srcs = ["test_graph.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_models",
    srcs = ["test_models.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "@pip//pytest",
        "@pip//sqlalchemy",
    ],
)

py_test(
    name = "test_schema_migrations",
    srcs = ["test_schema_migrations.py"],
    data = [
        "//database:role_initialization",
        "//infrastructure/docker:database_initialization",
        "//schemas:postgres_migrations",
    ],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/connectors/postgres",
        "@pip//pytest",
    ],
)
