load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_siglip",
    srcs = ["test_siglip.py"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/common",
        "//machine-learning/galadril-inference/src/galadril_inference/core",
        "//machine-learning/galadril-inference/src/galadril_inference/loading",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_model_downloads",
    srcs = ["test_model_downloads.py"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/models/audio",
        "//machine-learning/galadril-inference/src/galadril_inference/models/embedding",
        "//machine-learning/galadril-inference/src/galadril_inference/models/image",
        "//machine-learning/galadril-inference/src/galadril_inference/models/osint",
        "//machine-learning/galadril-inference/src/galadril_inference/models/temporal",
        "//machine-learning/galadril-inference/src/galadril_inference/models/text",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_runtime",
    srcs = ["test_runtime.py"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/models",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_onnx_models",
    srcs = ["test_onnx_models.py"],
    deps = [
        "//machine-learning/galadril-inference/src/galadril_inference/models/embedding",
        "//machine-learning/galadril-inference/src/galadril_inference/models/image",
        "@pip//numpy",
        "@pip//pytest",
    ],
)
