# gazelle:ignore

filegroup(
    name = "avro_schema",
    srcs = glob(["avro/*.avsc"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "postgres_migrations",
    srcs = [
        "postgres/README.md",
    ] + glob(["postgres/gateway_migrations/*.sql"]),
    visibility = ["//visibility:public"],
)

alias(
    name = "postgres_gateway_schema",
    actual = ":postgres_migrations",
    visibility = ["//visibility:public"],
)

alias(
    name = "spicedb_contract",
    actual = "//schemas/spicedb:spicedb_contract",
    visibility = ["//visibility:public"],
)

alias(
    name = "validate_spicedb_contract",
    actual = "//schemas/spicedb:validate_spicedb_contract",
    visibility = ["//visibility:public"],
)
