load("@rules_python//python:defs.bzl", "py_test")

package(default_visibility = ["//platform/vision/tests:__pkg__"])

py_test(
    name = "test_producer",
    srcs = ["test_producer.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_resolver",
    srcs = ["test_resolver.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_schemas_validator",
    srcs = ["test_schemas_validator.py"],
    legacy_create_init = False,
    deps = [
        "//platform/vision/src/galadril_vision/common",
        "//platform/vision/src/galadril_vision/connectors/kafka",
        "@pip//pytest",
    ],
)
