load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_architecture",
    srcs = ["test_architecture.py"],
    legacy_create_init = False,
    deps = ["//platform/ontology/src/galadril_ontology/backends/terminus"],
)

py_test(
    name = "test_model",
    srcs = ["test_model.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_service",
    srcs = ["test_service.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_domain_edges",
    srcs = ["test_domain_edges.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_repository_edges",
    srcs = ["test_repository_edges.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_runtime",
    srcs = ["test_runtime.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_service_edges",
    srcs = ["test_service_edges.py"],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_terminus",
    srcs = ["test_terminus.py"],
    legacy_create_init = False,
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "//platform/ontology/src/galadril_ontology/backends/terminus",
        "@pip//httpx",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_terminus_repository",
    srcs = ["test_terminus_repository.py"],
    legacy_create_init = False,
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "//platform/ontology/src/galadril_ontology/backends/terminus",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "test_terminus_integration",
    size = "large",
    srcs = ["test_terminus_integration.py"],
    legacy_create_init = False,
    tags = [
        "no-sandbox",
        "requires-docker",
    ],
    deps = [
        "//platform/ontology/src/galadril_ontology",
        "//platform/ontology/src/galadril_ontology/backends/terminus",
        "@pip//httpx",
        "@pip//testcontainers",
    ],
)
