load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "runtime",
    srcs = [
        "__init__.py",
        "batch.py",
        "engine.py",
        "schemas.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//platform/pipeline/src/galadril_pipeline/config",
        "@pip//pydantic",
    ],
)
