# gazelle:ignore

load("@rules_python//python:defs.bzl", "py_test")
load("//build:testing.bzl", "DOCKER_TEST_EXEC_PROPERTIES")

py_test(
    name = "proxy_test",
    size = "large",
    srcs = ["test_proxy.py"],
    main = "test_proxy.py",
    data = ["//infrastructure/envoy:configuration"],
    exec_properties = DOCKER_TEST_EXEC_PROPERTIES,
    legacy_create_init = False,
    tags = ["integration", "no-sandbox", "requires-docker"],
    deps = [
        "//infrastructure/envoy:testing",
        "@pip//cryptography",
        "@pip//docker",
        "@pip//httpx",
        "@pip//pyyaml",
    ],
)

py_test(
    name = "contract_test",
    srcs = ["test_contract.py"],
    main = "test_contract.py",
    data = [
        "//infrastructure/envoy:configuration",
        "//infrastructure/kubernetes:registry.yaml",
    ],
    legacy_create_init = False,
    deps = ["@pip//pyyaml"],
)
