"""Causal effect estimation using DoWhy."""

from dataclasses import dataclass
from typing import Optional

import networkx as nx
import pandas as pd
from dowhy import CausalModel
import structlog

from amarth.discovery.ensemble import EdgeStatus

logger = structlog.get_logger(__name__)


@dataclass
class CausalEstimateResult:
    """Container for the results of a DoWhy causal estimation."""

    treatment: str
    outcome: str
    ate: float
    edge_status: str
    is_significant: bool
    refutation_passed: bool
    method_name: str
    summary: str


class DowhyEstimator:
    """Estimates the causal effect of a treatment on an outcome using DoWhy.

    Acts as a bridge: sanitizes the discovered NetworkX DAG, initializes DoWhy,
    identifies the estimand, estimates the effect, and refutes the model.
    """

    def __init__(self, strict_dag: bool = True):
        """Initializes the DoWhy bridge.

        Args:
            strict_dag: If True, aggressively prunes uncertain edges to ensure
                        the graph is a DAG before passing it to DoWhy.
        """
        self.strict_dag = strict_dag

    def estimate_effect(
        self,
        df: pd.DataFrame,
        dag: nx.DiGraph,
        treatment: str,
        outcome: str,
        method_name: str = "backdoor.linear_regression",
    ) -> Optional[CausalEstimateResult]:
        """Estimates the ATE of treatment on outcome.

        Args:
            df: Input dataset.
            dag: The causal graph generated by the discovery phase.
            treatment: The name of the intervention variable.
            outcome: The name of the target variable.
            method_name: The DoWhy estimation method to use.

        Returns:
            A CausalEstimateResult object, or None if no causal path exists.
        """
        clean_dag = self._sanitize_graph(dag)

        if not nx.has_path(clean_dag, treatment, outcome):
            logger.info("no_causal_path", treatment=treatment, outcome=outcome)
            return None

        edge_status = (
            dag[treatment][outcome].get("status", "unknown")
            if dag.has_edge(treatment, outcome)
            else "indirect"
        )

        model = CausalModel(
            data=df, treatment=treatment, outcome=outcome, graph=clean_dag
        )

        try:
            identified_estimand = model.identify_effect(
                proceed_when_unidentifiable=False
            )
        except ValueError as e:
            logger.warning("unidentifiable_effect", error=str(e))
            return None

        estimate = model.estimate_effect(
            identified_estimand, method_name=method_name, test_significance=True
        )

        refute = model.refute_estimate(
            identified_estimand, estimate, method_name="random_common_cause"
        )
        refutation_passed = refute.new_effect is not None

        return CausalEstimateResult(
            treatment=treatment,
            outcome=outcome,
            ate=estimate.value,
            edge_status=edge_status,
            is_significant=estimate.test_stat_significance()
            if hasattr(estimate, "test_stat_significance")
            else True,
            refutation_passed=refutation_passed,
            method_name=method_name,
            summary=str(estimate),
        )

    def _sanitize_graph(self, dag: nx.DiGraph) -> nx.DiGraph:
        """Removes cycles and uncertain edges to satisfy DoWhy requirements."""
        clean_dag = dag.copy()

        if self.strict_dag:
            edges_to_remove = [
                (u, v)
                for u, v, d in clean_dag.edges(data=True)
                if d.get("status") == EdgeStatus.CONFLICT_DIRECTION.value
            ]
            clean_dag.remove_edges_from(edges_to_remove)

        while not nx.is_directed_acyclic_graph(clean_dag):
            try:
                cycle = nx.find_cycle(clean_dag)
                weakest_edge = min(
                    cycle,
                    key=lambda e: abs(clean_dag[e[0]][e[1]].get("weight", 1.0)),
                )
                clean_dag.remove_edge(*weakest_edge)
                logger.debug("cycle_broken", removed_edge=weakest_edge)
            except nx.NetworkXNoCycle:
                break

        return clean_dag
