apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-defaults
data:
  deployment: |
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
