name: Documentation CD

on:
  workflow_dispatch: # Allow manual runs.
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: mdBook
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: v0.5.4

      - name: Build mdBook
        run: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
